BEGIN TRANSACTION;
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Adaptability', 'Powers up moves of the same type.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Aerilate', 'Turns Normal-type moves into Flying-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Aftermath', 'Damages the attacker landing the finishing hit.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Air Lock', 'Eliminates the effects of weather.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Analytic', 'Boosts move power when the Pokémon moves last.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Anger Point', 'Maxes Attack after taking a critical hit.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Anger Shell', 'Lowers Defense/Sp. Def and raises Attack/Sp. Atk/Speed when HP drops below half.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Anticipation', 'Senses a foe''s dangerous moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Arena Trap', 'Prevents the foe from fleeing.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Armor Tail', 'Prevents opponent using priority moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Aroma Veil', 'Protects allies from attacks that limit their move choices.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('As One', 'Combines Unnerve and Chilling Neigh/Grim Neigh');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Aura Break', 'Reduces power of Dark- and Fairy-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Bad Dreams', 'Reduces a sleeping foe''s HP.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Ball Fetch', 'Retrieves a Poké Ball from a failed throw.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Battery', 'Raises power of teammates'' Special moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Battle Armor', 'The Pokémon is protected against critical hits.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Battle Bond', 'Transform into Ash-Greninja after causing opponent to faint.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Beads of Ruin', 'Lowers Special Defense of all Pokémon except itself.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Beast Boost', 'The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Berserk', 'Raises Special Attack when HP drops below half.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Big Pecks', 'Protects the Pokémon from Defense-lowering attacks.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Blaze', 'Powers up Fire-type moves in a pinch.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Bulletproof', 'Protects the Pokémon from ball and bomb moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Cheek Pouch', 'Restores additional HP when a Berry is consumed.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Chilling Neigh', 'Boosts Attack after knocking out a Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Chlorophyll', 'Boosts the Pokémon''s Speed in sunshine.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Clear Body', 'Prevents other Pokémon from lowering its stats.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Cloud Nine', 'Eliminates the effects of weather.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Color Change', 'Changes the Pokémon''s type to the foe''s move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Comatose', 'The Pokémon is always asleep but can still attack.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Commander', 'Goes inside the mouth of an ally Dondozo if one is on the field.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Competitive', 'Sharply raises Special Attack when the Pokémon''s stats are lowered.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Compound Eyes', 'The Pokémon''s accuracy is boosted.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Contrary', 'Makes stat changes have an opposite effect.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Corrosion', 'The Pokémon can poison Steel and Poison types.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Costar', 'Copies ally''s stat changes on entering battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Cotton Down', 'Lowers foe''s Speed when hit.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Cud Chew', 'Can eat the same Berry twice.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Curious Medicine', 'Resets all stat changes upon entering battlefield.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Cursed Body', 'May disable a move used on the Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Cute Charm', 'Contact with the Pokémon may cause infatuation.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Damp', 'Prevents the use of self-destructing moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Dancer', 'Copies the foe''s Dance moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Dark Aura', 'Raises power of Dark type moves for all Pokémon in battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Dauntless Shield', 'Boosts Defense in battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Dazzling', 'Protects the Pokémon from high-priority moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Defeatist', 'Lowers stats when HP drops below half.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Defiant', 'Sharply raises Attack when the Pokémon''s stats are lowered.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Delta Stream', 'Creates strong winds when the ability activates.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Desolate Land', 'Turns the sunlight extremely harsh when the ability activates.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Disguise', 'Avoids damage for one turn.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Download', 'Adjusts power according to a foe''s defenses.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Dragon''s Maw', 'Powers up Dragon-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Drizzle', 'The Pokémon makes it rain when it enters a battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Drought', 'Turns the sunlight harsh when the Pokémon enters a battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Dry Skin', 'Reduces HP if it is hot. Water restores HP.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Early Bird', 'The Pokémon awakens quickly from sleep.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Earth Eater', 'Restores HP when hit by a Ground-type move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Effect Spore', 'Contact may poison or cause paralysis or sleep.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Electric Surge', 'The Pokémon creates an Electric Terrain when it enters a battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Electromorphosis', 'Doubles power of the next Electric-type move when hit by an attack.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Embody Aspect', 'Boosts Attack/Defense/Sp. Def/Speed depending on the form.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Emergency Exit', 'Switches out when HP falls below 50%.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Fairy Aura', 'Raises power of Fairy type moves for all Pokémon in battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Filter', 'Reduces damage from super-effective attacks.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Flame Body', 'Contact with the Pokémon may burn the attacker.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Flare Boost', 'Powers up special attacks when burned.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Flash Fire', 'It powers up Fire-type moves if it''s hit by one.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Flower Gift', 'Powers up party Pokémon when it is sunny.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Flower Veil', 'Prevents lowering of ally Grass-type Pokémon''s stats.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Fluffy', 'Halves damage from contact moves, but doubles damage from Fire-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Forecast', 'Castform transforms with the weather.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Forewarn', 'Determines what moves a foe has.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Friend Guard', 'Reduces damage done to allies.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Frisk', 'The Pokémon can check a foe''s held item.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Full Metal Body', 'Prevents other Pokémon from lowering its stats.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Fur Coat', 'Reduces damage from physical moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Gale Wings', 'Gives priority to Flying-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Galvanize', 'Normal-type moves become Electric-type moves and their power boosted.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Gluttony', 'Encourages the early use of a held Berry.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Good as Gold', 'Gives immunity to status moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Gooey', 'Contact with the Pokémon lowers the attacker''s Speed stat.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Gorilla Tactics', 'Boosts the Pokémon''s Attack stat but only allows the use of the first selected move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Grass Pelt', 'Boosts the Defense stat in Grassy Terrain.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Grassy Surge', 'The Pokémon creates a Grassy Terrain when it enters a battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Grim Neigh', 'Boosts Special Attack after knocking out a Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Guard Dog', 'Boosts Attack if intimidated, and prevents being forced to switch out.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Gulp Missile', 'Returns with a catch in its mouth after using Surf or Dive.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Guts', 'Boosts Attack if there is a status problem.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Hadron Engine', 'Creates an Electric Terrain when entering battle, and boosts Special Attack while active.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Harvest', 'May create another Berry after one is used.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Healer', 'May heal an ally''s status conditions.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Heatproof', 'Weakens the power of Fire-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Heavy Metal', 'Doubles the Pokémon''s weight.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Honey Gather', 'The Pokémon may gather Honey from somewhere.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Hospitality', 'Partially restores an ally''s HP when it enters a battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Huge Power', 'Raises the Pokémon''s Attack stat.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Hunger Switch', 'Changes forms each turn.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Hustle', 'Boosts the Attack stat, but lowers accuracy.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Hydration', 'Heals status problems if it is raining.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Hyper Cutter', 'Prevents other Pokémon from lowering Attack stat.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Ice Body', 'The Pokémon gradually regains HP in a hailstorm.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Ice Face', 'Avoids damage from Physical moves for one turn.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Ice Scales', 'Halves damage from Special moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Illuminate', 'Raises the likelihood of meeting wild Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Illusion', 'Enters battle disguised as the last Pokémon in the party.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Immunity', 'Prevents the Pokémon from getting poisoned.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Imposter', 'It transforms itself into the Pokémon it is facing.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Infiltrator', 'Passes through the foe''s barrier and strikes.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Innards Out', 'Deals damage upon fainting.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Inner Focus', 'The Pokémon is protected from flinching.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Insomnia', 'Prevents the Pokémon from falling asleep.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Intimidate', 'Lowers the foe''s Attack stat.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Intrepid Sword', 'Boosts Attack in battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Iron Barbs', 'Inflicts damage to the Pokémon on contact.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Iron Fist', 'Boosts the power of punching moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Justified', 'Raises Attack when hit by a Dark-type move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Keen Eye', 'Prevents other Pokémon from lowering accuracy.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Klutz', 'The Pokémon can''t use any held items.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Leaf Guard', 'Prevents problems with status in sunny weather.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Levitate', 'Gives immunity to Ground type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Libero', 'Changes the Pokémon''s type to its last used move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Light Metal', 'Halves the Pokémon''s weight.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Lightning Rod', 'Draws in all Electric-type moves to up Sp. Attack.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Limber', 'The Pokémon is protected from paralysis.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Lingering Aroma', 'Contact changes the attacker''s Ability to Lingering Aroma.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Liquid Ooze', 'Damages attackers using any draining move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Liquid Voice', 'All sound-based moves become Water-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Long Reach', 'The Pokémon uses its moves without making contact with the target.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Magic Bounce', 'Reflects status- changing moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Magic Guard', 'Protects the Pokémon from indirect damage.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Magician', 'The Pokémon steals the held item of a Pokémon it hits with a move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Magma Armor', 'Prevents the Pokémon from becoming frozen.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Magnet Pull', 'Prevents Steel-type Pokémon from escaping.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Marvel Scale', 'Ups Defense if there is a status problem.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Mega Launcher', 'Boosts the power of aura and pulse moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Merciless', 'The Pokémon''s attacks become critical hits if the target is poisoned.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Mimicry', 'Changes type depending on the terrain.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Mind''s Eye', 'Ignores opponent''s Evasiveness, and allows Normal- and Fighting-type attacks to hit Ghosts.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Minus', 'Ups Sp. Atk if another Pokémon has Plus or Minus.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Mirror Armor', 'Reflects any stat-lowering effects.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Misty Surge', 'The Pokémon creates a Misty Terrain when it enters a battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Mold Breaker', 'Moves can be used regardless of Abilities.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Moody', 'Raises one stat and lowers another.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Motor Drive', 'Raises Speed if hit by an Electric-type move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Moxie', 'Boosts Attack after knocking out any Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Multiscale', 'Reduces damage when HP is full.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Multitype', 'Changes type to match the held Plate.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Mummy', 'Contact with this Pokémon spreads this Ability.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Mycelium Might', 'Status moves go last, but are not affected by the opponent''s ability.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Natural Cure', 'All status problems heal when it switches out.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Neuroforce', 'Powers up moves that are super effective.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Neutralizing Gas', 'Neutralizes abilities of all Pokémon in battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('No Guard', 'Ensures attacks by or against the Pokémon land.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Normalize', 'All the Pokémon''s moves become the Normal type.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Oblivious', 'Prevents it from becoming infatuated.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Opportunist', 'Copies stat boosts by the opponent.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Orichalcum Pulse', 'Turns the sunlight harsh when entering battle, and boosts Attack while active.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Overcoat', 'Protects the Pokémon from weather damage.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Overgrow', 'Powers up Grass-type moves in a pinch.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Own Tempo', 'Prevents the Pokémon from becoming confused.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Parental Bond', 'Allows the Pokémon to attack twice.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Pastel Veil', 'Prevents the Pokémon and its allies from being poisoned.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Perish Body', 'When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Pickpocket', 'Steals an item when hit by another Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Pickup', 'The Pokémon may pick up items.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Pixilate', 'Turns Normal-type moves into Fairy-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Plus', 'Ups Sp. Atk if another Pokémon has Plus or Minus.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Poison Heal', 'Restores HP if the Pokémon is poisoned.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Poison Point', 'Contact with the Pokémon may poison the attacker.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Poison Puppeteer', 'Poisoned Pokémon also become confused.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Poison Touch', 'May poison targets when a Pokémon makes contact.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Power Construct', 'Changes form when HP drops below half.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Power of Alchemy', 'The Pokémon copies the Ability of a defeated ally.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Power Spot', 'Just being next to the Pokémon powers up moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Prankster', 'Gives priority to a status move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Pressure', 'The Pokémon raises the foe''s PP usage.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Primordial Sea', 'Makes it rain heavily when the ability activates.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Prism Armor', 'Reduces damage from super-effective attacks.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Propeller Tail', 'Ignores moves and abilities that draw in moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Protean', 'Changes the Pokémon''s type to its last used move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Protosynthesis', 'Raises highest stat in harsh sunlight, or if holding Booster Energy.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Psychic Surge', 'The Pokémon creates a Psychic Terrain when it enters a battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Punk Rock', 'Boosts sound-based moves and halves damage from the same moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Pure Power', 'Raises the Pokémon''s Attack stat.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Purifying Salt', 'Protects from status conditions and halves damage from Ghost-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Quark Drive', 'Raises highest stat on Electric Terrain, or if holding Booster Energy.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Queenly Majesty', 'Prevents use of priority moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Quick Draw', '');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Quick Feet', 'Boosts Speed if there is a status problem.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Rain Dish', 'The Pokémon gradually regains HP in rain.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Rattled', 'Bug, Ghost or Dark type moves scare it and boost its Speed.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Receiver', 'Inherits an ally''s ability when it faints.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Reckless', 'Powers up moves that have recoil damage.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Refrigerate', 'Turns Normal-type moves into Ice-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Regenerator', 'Restores a little HP when withdrawn from battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Ripen', 'Doubles the effect of berries.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Rivalry', 'Deals more damage to a Pokémon of same gender.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('RKS System', 'Changes type depending on held item.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Rock Head', 'Protects the Pokémon from recoil damage.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Rocky Payload', 'Powers up Rock-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Rough Skin', 'Inflicts damage to the attacker on contact.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Run Away', 'Enables a sure getaway from wild Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sand Force', 'Boosts certain moves'' power in a sandstorm.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sand Rush', 'Boosts the Pokémon''s Speed in a sandstorm.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sand Spit', 'Creates a sandstorm when hit by an attack.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sand Stream', 'The Pokémon summons a sandstorm in battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sand Veil', 'Boosts the Pokémon''s evasion in a sandstorm.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sap Sipper', 'Boosts Attack when hit by a Grass-type move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Schooling', 'Changes Wishiwashi to School Form.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Scrappy', 'Enables moves to hit Ghost-type Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Screen Cleaner', 'Nullifies effects of Light Screen, Reflect, and Aurora Veil.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Seed Sower', 'Turns the ground into Grassy Terrain when the Pokémon is hit by an attack.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Serene Grace', 'Boosts the likelihood of added effects appearing.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Shadow Shield', 'Reduces damage when HP is full.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Shadow Tag', 'Prevents the foe from escaping.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sharpness', 'Boosts the power of slicing moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Shed Skin', 'The Pokémon may heal its own status problems.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sheer Force', 'Removes added effects to increase move damage.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Shell Armor', 'The Pokémon is protected against critical hits.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Shield Dust', 'Blocks the added effects of attacks taken.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Shields Down', 'Changes stats when HP drops below half.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Simple', 'Doubles all stat changes.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Skill Link', 'Increases the frequency of multi-strike moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Slow Start', 'Temporarily halves Attack and Speed.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Slush Rush', 'Boosts the Pokémon''s Speed stat in a hailstorm.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sniper', 'Powers up moves if they become critical hits.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Snow Cloak', 'Raises evasion in a hailstorm.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Snow Warning', 'The Pokémon summons a hailstorm in battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Solar Power', 'In sunshine, Sp. Atk is boosted but HP decreases.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Solid Rock', 'Reduces damage from super-effective attacks.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Soul-Heart', 'Raises Special Attack when another Pokémon faints.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Soundproof', 'Gives immunity to sound-based moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Speed Boost', 'Its Speed stat is gradually boosted.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Stakeout', 'Deals double damage to Pokémon switching in.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Stall', 'The Pokémon moves after all other Pokémon do.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Stalwart', 'Ignores moves and abilities that draw in moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Stamina', 'Raises Defense when attacked.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Stance Change', 'Changes form depending on moves used.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Static', 'Contact with the Pokémon may cause paralysis.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Steadfast', 'Raises Speed each time the Pokémon flinches.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Steam Engine', 'Drastically raises Speed when hit by a Fire- or Water-type move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Steelworker', 'Powers up Steel-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Steely Spirit', 'Powers up ally Pokémon''s Steel-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Stench', 'The stench may cause the target to flinch.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sticky Hold', 'Protects the Pokémon from item theft.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Storm Drain', 'Draws in all Water-type moves to up Sp. Attack.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Strong Jaw', 'Boosts the power of biting moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sturdy', 'It cannot be knocked out with one hit.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Suction Cups', 'Negates all moves that force switching out.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Super Luck', 'Heightens the critical-hit ratios of moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Supersweet Syrup', 'Lowers opponent''s Evasiveness when entering battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Supreme Overlord', 'Attack and Special Attack are boosted for each party Pokémon that has been defeated.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Surge Surfer', 'Doubles Speed during Electric Terrain.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Swarm', 'Powers up Bug-type moves in a pinch.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sweet Veil', 'Prevents the Pokémon and allies from falling asleep.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Swift Swim', 'Boosts the Pokémon''s Speed in rain.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Sword of Ruin', 'Lowers Defense of all Pokémon except itself.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Symbiosis', 'The Pokémon can pass an item to an ally.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Synchronize', 'Passes a burn, poison, or paralysis to the foe.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Tablets of Ruin', 'Lowers Attack of all Pokémon except itself.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Tangled Feet', 'Raises evasion if the Pokémon is confused.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Tangling Hair', 'Contact with the Pokémon lowers the attacker''s Speed stat.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Technician', 'Powers up the Pokémon''s weaker moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Telepathy', 'Anticipates an ally''s attack and dodges it.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Tera Shell', 'Moves are not very effective when HP is full.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Tera Shift', 'Transforms into Terastal Form in battle.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Teraform Zero', 'Eliminates all effects of weather and terrain.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Teravolt', 'Moves can be used regardless of Abilities.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Thermal Exchange', 'Raises Attack when hit by a Fire-type move. Cannot be burned.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Thick Fat', 'Ups resistance to Fire- and Ice-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Tinted Lens', 'Powers up “not very effective” moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Torrent', 'Powers up Water-type moves in a pinch.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Tough Claws', 'Boosts the power of contact moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Toxic Boost', 'Powers up physical attacks when poisoned.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Toxic Chain', 'May cause bad poisoning.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Toxic Debris', 'Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Trace', 'The Pokémon copies a foe''s Ability.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Transistor', 'Powers up Electric-type moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Triage', 'Gives priority to restorative moves.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Truant', 'Pokémon can''t attack on consecutive turns.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Turboblaze', 'Moves can be used regardless of Abilities.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Unaware', 'Ignores any stat changes in the Pokémon.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Unburden', 'Raises Speed if a held item is used.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Unnerve', 'Makes the foe nervous and unable to eat Berries.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Unseen Fist', 'Contact moves can strike through Protect/Detect.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Vessel of Ruin', 'Lowers Special Attack of all Pokémon except itself.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Victory Star', 'Boosts the accuracy of its allies and itself.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Vital Spirit', 'Prevents the Pokémon from falling asleep.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Volt Absorb', 'Restores HP if hit by an Electric-type move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Wandering Spirit', 'Swaps abilities with opponents on contact.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Water Absorb', 'Restores HP if hit by a Water-type move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Water Bubble', 'Halves damage from Fire-type moves, doubles power of Water-type moves used, and prevents burns.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Water Compaction', 'Sharply raises Defense when hit by a Water-type move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Water Veil', 'Prevents the Pokémon from getting a burn.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Weak Armor', 'Physical attacks lower Defense and raise Speed.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Well-Baked Body', 'Immune to Fire-type moves, and Defense is sharply boosted.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('White Smoke', 'Prevents other Pokémon from lowering its stats.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Wimp Out', 'Switches out when HP drops below half.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Wind Power', 'Doubles power of the next Electric-type move used, when hit by a wind move.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Wind Rider', 'Takes no damage from wind moves, and boosts Attack if hit by one.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Wonder Guard', 'Only supereffective moves will hit.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Wonder Skin', 'Makes status-changing moves more likely to miss.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Zen Mode', 'Changes form when HP drops below half.');
INSERT INTO abilities (ability_name, ability_effect) VALUES ('Zero to Hero', 'Transforms into its Hero Form when switching out.');
COMMIT;