BEGIN TRANSACTION;
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Hardy', 'none', 'none');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Lonely', 'attack', 'defense');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Brave', 'attack', 'speed');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Adamant', 'attack', 'special_attack');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Naughty', 'attack', 'special_defense');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Bold', 'defense', 'attack');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Docile', 'none', 'none');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Relaxed', 'defense', 'speed');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Impish', 'defense', 'special_attack');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Lax', 'defense', 'special_defense');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Timid', 'speed', 'attack');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Hasty', 'speed', 'defense');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Serious', 'none', 'none');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Jolly', 'speed', 'special_attack');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('NaÔve', 'speed', 'special_defense');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Modest', 'special_attack', 'attack');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Mild', 'special_attack', 'defense');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Quiet', 'special_attack', 'speed');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Bashful', 'none', 'none');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Rash', 'special_attack', 'special_defense');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Calm', 'special_defense', 'attack');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Gentle', 'special_defense', 'defense');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Sassy', 'special_defense', 'speed');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Careful', 'special_defense', 'special_attack');
INSERT INTO nature (nature_name, nature_increase, nature_decrease) VALUES ('Quirky', 'none', 'none');
COMMIT;