BEGIN TRANSACTION;
INSERT INTO types (type_name) VALUES ('Normal');
INSERT INTO types (type_name) VALUES ('Fire');
INSERT INTO types (type_name) VALUES ('Water');
INSERT INTO types (type_name) VALUES ('Electric');
INSERT INTO types (type_name) VALUES ('Grass');
INSERT INTO types (type_name) VALUES ('Ice');
INSERT INTO types (type_name) VALUES ('Fighting');
INSERT INTO types (type_name) VALUES ('Poison');
INSERT INTO types (type_name) VALUES ('Ground');
INSERT INTO types (type_name) VALUES ('Flying');
INSERT INTO types (type_name) VALUES ('Psychic');
INSERT INTO types (type_name) VALUES ('Bug');
INSERT INTO types (type_name) VALUES ('Rock');
INSERT INTO types (type_name) VALUES ('Ghost');
INSERT INTO types (type_name) VALUES ('Dragon');
INSERT INTO types (type_name) VALUES ('Dark');
INSERT INTO types (type_name) VALUES ('Steel');
INSERT INTO types (type_name) VALUES ('Fairy');
COMMIT;